export default [{
        NPI: "1033112214",
        Entity_Type_Code: "Individual",
        Replacement_NPI: "",
        Employer_Identification_Number: "",
        ProviderOrganizationName_Legal_Business_Name: "",
        ProviderLastName_Legal_Name: "KOENIG",
        Provider_First_Name: "MARK",
        Provider_Middle_Name: "",
        Provider_Name_Prefix_Text: "",
        Provider_Name_Suffix_Text: " ",
        Provider_Credential_Text: "D.O.",
        Provider_Other_Organization_Name: "",
        Provider_Other_Organization_Name_Type_Code: "",
        Provider_Other_Last_Name: "",
        Provider_Other_First_Name: "",
        Provider_Other_Middle_Name: "",
        Provider_Other_Name_Prefix_Text: "",
        Provider_Other_Name_Suffix_Text: "",
        Provider_Other_Credential_Text: "",
        Provider_Other_Last_Name_Type_Code: "",
        Provider_First_Line_Business_Mailing_Address: "11279 PERRY HWY",
        Provider_Second_Line_Business_Mailing_Address: "STE 450",
        Provider_Business_Mailing_Address_City_Name: "WEXFORD",
        Provider_Business_Mailing_Address_State_Name: "PA",
        Provider_Business_Mailing_Address_Postal_Code: "150909303",
        Provider_Business_Mailing_Address_Country_Code: "US",
        Provider_Business_Mailing_Address_Telephone_Number: "",
        Provider_Business_Mailing_Address_Fax_Number: "",
        Provider_First_Line_Business_Practice_Location_Address: "604 EPSILON DR",
        Provider_Second_Line_Business_Practice_Location_Address: "",
        Provider_Business_Practice_Location_Address_City_Name: "PITTSBURGH",
        Provider_Business_Practice_Location_Address_State_Name: "PA",
        Provider_Business_Practice_Location_Address_Postal_Code: "152382808",
        Provider_Business_Practice_Location_Address_Country_Code: "US",
        Provider_Business_Practice_Location_Address_Telephone_Number: "4129679090",
        Provider_Business_Practice_Location_Address_Fax_Number: "",
        Provider_Enumeration_Date: "05/23/2005",
        Last_Update_Date: "03/25/2021",
        NPI_Deactivation_Reason_Code: "",
        NPI_Deactivation_Date: "",
        NPI_Reactivation_Date: "",
        Provider_Gender_Code: "M",
        Authorized_Official_Last_Name: "",
        Authorized_Official_First_Name: "",
        Authorized_Official_Middle_Name: "",
        Authorized_Official_Title_Or_Position: "",
        Authorized_Official_Telephone_Number: "",
        Is_Sole_Proprietor: "No",
        Is_Organization_Subpart: "",
        Parent_Organization_LBN: "",
        Parent_Organization_TIN: "",
        Authorized_Official_Name_Prefix_Text: "",
        Authorized_Official_Name_Suffix_Text: "",
        Authorized_Official_Credential_Text: "",
        Certification_Date: "",
        HealthcareProviderData: [
            {
                Healthcare_Provider: "Healthcare Provider 1",
                Healthcare_Provider_Taxonomy_Code: "208000000X",
                Provider_License_Number: "MD022712E",
                Provider_License_Number_State_Code: "PA",
                Healthcare_Provider_Primary_Taxonomy_Switch: "Yes"
            }
        ],
        HealthcareProviderTaxonomyGroupData: [],
        OtherProviderData: [],
        OtherNameReferenceLayout: [],
        PracticeLocationReferenceLayout: [],
        Endpoint_Layout: [
            {
                Endpoint_Type: "DIRECT",
                Endpoint_Type_Description: "Direct Messaging Address",
                Endpoint: "mark.a.koenig@upmcdirect.com",
                Affiliation: "Y",
                Endpoint_Description: "",
                Affiliation_Legal_Business_Name: "UPMC",
                Use_Code: "",
                Use_Description: "",
                Other_Use_Description: "",
                Content_Type: "",
                Content_Description: "",
                Other_Content_Description: "",
                Affiliation_Address_Line_One: "600 Grant St",
                Affiliation_Address_Line_Two: "Floor 58",
                Affiliation_Address_City: "Pittsburgh",
                Affiliation_Address_State: "PA",
                Affiliation_Address_Country: "US",
                Affiliation_Address_Postal_Code: "152192702"
            }
        ]
    },
        {
            NPI: "1497898829",
            Entity_Type_Code: "Individual",
            Replacement_NPI: "",
            Employer_Identification_Number: "",
            ProviderOrganizationName_Legal_Business_Name: "",
            ProviderLastName_Legal_Name: "WILSON",
            Provider_First_Name: "STEVEN",
            Provider_Middle_Name: "B.",
            Provider_Name_Prefix_Text: "",
            Provider_Name_Suffix_Text: " ",
            Provider_Credential_Text: "M.D.",
            Provider_Other_Organization_Name: "",
            Provider_Other_Organization_Name_Type_Code: "",
            Provider_Other_Last_Name: "",
            Provider_Other_First_Name: "",
            Provider_Other_Middle_Name: "",
            Provider_Other_Name_Prefix_Text: "",
            Provider_Other_Name_Suffix_Text: "",
            Provider_Other_Credential_Text: "",
            Provider_Other_Last_Name_Type_Code: "",
            Provider_First_Line_Business_Mailing_Address: "5708 WOLFGANG SCHOOL RD",
            Provider_Second_Line_Business_Mailing_Address: "",
            Provider_Business_Mailing_Address_City_Name: "GLEN ROCK",
            Provider_Business_Mailing_Address_State_Name: "PA",
            Provider_Business_Mailing_Address_Postal_Code: "173278891",
            Provider_Business_Mailing_Address_Country_Code: "US",
            Provider_Business_Mailing_Address_Telephone_Number: "7172354178",
            Provider_Business_Mailing_Address_Fax_Number: "",
            Provider_First_Line_Business_Practice_Location_Address: "5708 WOLFGANG SCHOOL RD",
            Provider_Second_Line_Business_Practice_Location_Address: "",
            Provider_Business_Practice_Location_Address_City_Name: "GLEN ROCK",
            Provider_Business_Practice_Location_Address_State_Name: "PA",
            Provider_Business_Practice_Location_Address_Postal_Code: "173278891",
            Provider_Business_Practice_Location_Address_Country_Code: "US",
            Provider_Business_Practice_Location_Address_Telephone_Number: "7172354178",
            Provider_Business_Practice_Location_Address_Fax_Number: "",
            Provider_Enumeration_Date: "02/15/2007",
            Last_Update_Date: "07/08/2007",
            NPI_Deactivation_Reason_Code: "",
            NPI_Deactivation_Date: "",
            NPI_Reactivation_Date: "",
            Provider_Gender_Code: "M",
            Authorized_Official_Last_Name: "",
            Authorized_Official_First_Name: "",
            Authorized_Official_Middle_Name: "",
            Authorized_Official_Title_Or_Position: "",
            Authorized_Official_Telephone_Number: "",
            Is_Sole_Proprietor: "Yes",
            Is_Organization_Subpart: "",
            Parent_Organization_LBN: "",
            Parent_Organization_TIN: "",
            Authorized_Official_Name_Prefix_Text: "",
            Authorized_Official_Name_Suffix_Text: "",
            Authorized_Official_Credential_Text: "",
            Certification_Date: "",
            HealthcareProviderData: [
                {
                    Healthcare_Provider: "Healthcare Provider 1",
                    Healthcare_Provider_Taxonomy_Code: "2084P0800X",
                    Provider_License_Number: "MD020407E",
                    Provider_License_Number_State_Code: "PA",
                    Healthcare_Provider_Primary_Taxonomy_Switch: "Yes"
                }
            ],
            HealthcareProviderTaxonomyGroupData: [],
            OtherProviderData: [],
            OtherNameReferenceLayout: [],
            PracticeLocationReferenceLayout: [],
            Endpoint_Layout: []
        },
        {
            NPI: "1811972656",
            Entity_Type_Code: "Individual",
            Replacement_NPI: "",
            Employer_Identification_Number: "",
            ProviderOrganizationName_Legal_Business_Name: "",
            ProviderLastName_Legal_Name: "FEATHERMAN",
            Provider_First_Name: "RODNEY",
            Provider_Middle_Name: "E",
            Provider_Name_Prefix_Text: "DR.",
            Provider_Name_Suffix_Text: " ",
            Provider_Credential_Text: "M.D.",
            Provider_Other_Organization_Name: "",
            Provider_Other_Organization_Name_Type_Code: "",
            Provider_Other_Last_Name: "",
            Provider_Other_First_Name: "",
            Provider_Other_Middle_Name: "",
            Provider_Other_Name_Prefix_Text: "",
            Provider_Other_Name_Suffix_Text: "",
            Provider_Other_Credential_Text: "",
            Provider_Other_Last_Name_Type_Code: "",
            Provider_First_Line_Business_Mailing_Address: "PO BOX 5024",
            Provider_Second_Line_Business_Mailing_Address: "",
            Provider_Business_Mailing_Address_City_Name: "NEW YORK",
            Provider_Business_Mailing_Address_State_Name: "NY",
            Provider_Business_Mailing_Address_Postal_Code: "100875024",
            Provider_Business_Mailing_Address_Country_Code: "US",
            Provider_Business_Mailing_Address_Telephone_Number: "8006274470",
            Provider_Business_Mailing_Address_Fax_Number: "4129375710",
            Provider_First_Line_Business_Practice_Location_Address: "1 GUSTAVE L LEVY PL",
            Provider_Second_Line_Business_Practice_Location_Address: "ANESTHESIOLOGY - BOX 1010",
            Provider_Business_Practice_Location_Address_City_Name: "NEW YORK",
            Provider_Business_Practice_Location_Address_State_Name: "NY",
            Provider_Business_Practice_Location_Address_Postal_Code: "100296500",
            Provider_Business_Practice_Location_Address_Country_Code: "US",
            Provider_Business_Practice_Location_Address_Telephone_Number: "8006274470",
            Provider_Business_Practice_Location_Address_Fax_Number: "4129375767",
            Provider_Enumeration_Date: "12/14/2005",
            Last_Update_Date: "01/09/2015",
            NPI_Deactivation_Reason_Code: "",
            NPI_Deactivation_Date: "",
            NPI_Reactivation_Date: "",
            Provider_Gender_Code: "M",
            Authorized_Official_Last_Name: "",
            Authorized_Official_First_Name: "",
            Authorized_Official_Middle_Name: "",
            Authorized_Official_Title_Or_Position: "",
            Authorized_Official_Telephone_Number: "",
            Is_Sole_Proprietor: "No",
            Is_Organization_Subpart: "",
            Parent_Organization_LBN: "",
            Parent_Organization_TIN: "",
            Authorized_Official_Name_Prefix_Text: "",
            Authorized_Official_Name_Suffix_Text: "",
            Authorized_Official_Credential_Text: "",
            Certification_Date: "",
            HealthcareProviderData: [
                {
                    Healthcare_Provider: "Healthcare Provider 1",
                    Healthcare_Provider_Taxonomy_Code: "207L00000X",
                    Provider_License_Number: "156749",
                    Provider_License_Number_State_Code: "NY",
                    Healthcare_Provider_Primary_Taxonomy_Switch: "Yes"
                }
            ],
            HealthcareProviderTaxonomyGroupData: [],
            OtherProviderData: [
                {
                    Provider: "Provider 1",
                    Other_Provider_Identifier: "00958347",
                    Other_Provider_Identifier_Type_Code: "MEDICAID",
                    Other_Provider_Identifier_State: "NY",
                    Other_Provider_Identifier_Issuer: ""
                }
            ],
            OtherNameReferenceLayout: [],
            PracticeLocationReferenceLayout: [],
            Endpoint_Layout: []
        },
    {
        NPI: "2497898829",
        Entity_Type_Code: "Individual",
        Replacement_NPI: "",
        Employer_Identification_Number: "",
        ProviderOrganizationName_Legal_Business_Name: "",
        ProviderLastName_Legal_Name: "DOOLEY",
        Provider_First_Name: "RICHARD",
        Provider_Middle_Name: "B.",
        Provider_Name_Prefix_Text: "",
        Provider_Name_Suffix_Text: " ",
        Provider_Credential_Text: "M.D.",
        Provider_Other_Organization_Name: "",
        Provider_Other_Organization_Name_Type_Code: "",
        Provider_Other_Last_Name: "",
        Provider_Other_First_Name: "",
        Provider_Other_Middle_Name: "",
        Provider_Other_Name_Prefix_Text: "",
        Provider_Other_Name_Suffix_Text: "",
        Provider_Other_Credential_Text: "",
        Provider_Other_Last_Name_Type_Code: "",
        Provider_First_Line_Business_Mailing_Address: "5708 WOLFGANG SCHOOL RD",
        Provider_Second_Line_Business_Mailing_Address: "",
        Provider_Business_Mailing_Address_City_Name: "GLEN ROCK",
        Provider_Business_Mailing_Address_State_Name: "PA",
        Provider_Business_Mailing_Address_Postal_Code: "173278891",
        Provider_Business_Mailing_Address_Country_Code: "US",
        Provider_Business_Mailing_Address_Telephone_Number: "7172354178",
        Provider_Business_Mailing_Address_Fax_Number: "",
        Provider_First_Line_Business_Practice_Location_Address: "5708 WOLFGANG SCHOOL RD",
        Provider_Second_Line_Business_Practice_Location_Address: "",
        Provider_Business_Practice_Location_Address_City_Name: "GLEN ROCK",
        Provider_Business_Practice_Location_Address_State_Name: "PA",
        Provider_Business_Practice_Location_Address_Postal_Code: "173278891",
        Provider_Business_Practice_Location_Address_Country_Code: "US",
        Provider_Business_Practice_Location_Address_Telephone_Number: "7172354178",
        Provider_Business_Practice_Location_Address_Fax_Number: "",
        Provider_Enumeration_Date: "02/15/2007",
        Last_Update_Date: "07/08/2007",
        NPI_Deactivation_Reason_Code: "",
        NPI_Deactivation_Date: "",
        NPI_Reactivation_Date: "",
        Provider_Gender_Code: "M",
        Authorized_Official_Last_Name: "",
        Authorized_Official_First_Name: "",
        Authorized_Official_Middle_Name: "",
        Authorized_Official_Title_Or_Position: "",
        Authorized_Official_Telephone_Number: "",
        Is_Sole_Proprietor: "Yes",
        Is_Organization_Subpart: "",
        Parent_Organization_LBN: "",
        Parent_Organization_TIN: "",
        Authorized_Official_Name_Prefix_Text: "",
        Authorized_Official_Name_Suffix_Text: "",
        Authorized_Official_Credential_Text: "",
        Certification_Date: "",
        HealthcareProviderData: [
            {
                Healthcare_Provider: "Healthcare Provider 1",
                Healthcare_Provider_Taxonomy_Code: "2084P0800X",
                Provider_License_Number: "MD020407E",
                Provider_License_Number_State_Code: "PA",
                Healthcare_Provider_Primary_Taxonomy_Switch: "Yes"
            }
        ],
        HealthcareProviderTaxonomyGroupData: [],
        OtherProviderData: [],
        OtherNameReferenceLayout: [],
        PracticeLocationReferenceLayout: [],
        Endpoint_Layout: []
    },
    {
        NPI: "W033112214",
        Entity_Type_Code: "Individual",
        Replacement_NPI: "",
        Employer_Identification_Number: "",
        ProviderOrganizationName_Legal_Business_Name: "",
        ProviderLastName_Legal_Name: "VANDERGRIFT",
        Provider_First_Name: "GREGORY",
        Provider_Middle_Name: "",
        Provider_Name_Prefix_Text: "",
        Provider_Name_Suffix_Text: " ",
        Provider_Credential_Text: "D.O.",
        Provider_Other_Organization_Name: "",
        Provider_Other_Organization_Name_Type_Code: "",
        Provider_Other_Last_Name: "",
        Provider_Other_First_Name: "",
        Provider_Other_Middle_Name: "",
        Provider_Other_Name_Prefix_Text: "",
        Provider_Other_Name_Suffix_Text: "",
        Provider_Other_Credential_Text: "",
        Provider_Other_Last_Name_Type_Code: "",
        Provider_First_Line_Business_Mailing_Address: "11279 PERRY HWY",
        Provider_Second_Line_Business_Mailing_Address: "STE 450",
        Provider_Business_Mailing_Address_City_Name: "WEXFORD",
        Provider_Business_Mailing_Address_State_Name: "PA",
        Provider_Business_Mailing_Address_Postal_Code: "150909303",
        Provider_Business_Mailing_Address_Country_Code: "US",
        Provider_Business_Mailing_Address_Telephone_Number: "",
        Provider_Business_Mailing_Address_Fax_Number: "",
        Provider_First_Line_Business_Practice_Location_Address: "604 EPSILON DR",
        Provider_Second_Line_Business_Practice_Location_Address: "",
        Provider_Business_Practice_Location_Address_City_Name: "PITTSBURGH",
        Provider_Business_Practice_Location_Address_State_Name: "PA",
        Provider_Business_Practice_Location_Address_Postal_Code: "152382808",
        Provider_Business_Practice_Location_Address_Country_Code: "US",
        Provider_Business_Practice_Location_Address_Telephone_Number: "4129679090",
        Provider_Business_Practice_Location_Address_Fax_Number: "",
        Provider_Enumeration_Date: "05/23/2005",
        Last_Update_Date: "03/25/2021",
        NPI_Deactivation_Reason_Code: "",
        NPI_Deactivation_Date: "",
        NPI_Reactivation_Date: "",
        Provider_Gender_Code: "M",
        Authorized_Official_Last_Name: "",
        Authorized_Official_First_Name: "",
        Authorized_Official_Middle_Name: "",
        Authorized_Official_Title_Or_Position: "",
        Authorized_Official_Telephone_Number: "",
        Is_Sole_Proprietor: "No",
        Is_Organization_Subpart: "",
        Parent_Organization_LBN: "",
        Parent_Organization_TIN: "",
        Authorized_Official_Name_Prefix_Text: "",
        Authorized_Official_Name_Suffix_Text: "",
        Authorized_Official_Credential_Text: "",
        Certification_Date: "",
        HealthcareProviderData: [
            {
                Healthcare_Provider: "Healthcare Provider 1",
                Healthcare_Provider_Taxonomy_Code: "208000000X",
                Provider_License_Number: "MD022712E",
                Provider_License_Number_State_Code: "PA",
                Healthcare_Provider_Primary_Taxonomy_Switch: "Yes"
            }
        ],
        HealthcareProviderTaxonomyGroupData: [],
        OtherProviderData: [],
        OtherNameReferenceLayout: [],
        PracticeLocationReferenceLayout: [],
        Endpoint_Layout: [
            {
                Endpoint_Type: "DIRECT",
                Endpoint_Type_Description: "Direct Messaging Address",
                Endpoint: "mark.a.koenig@upmcdirect.com",
                Affiliation: "Y",
                Endpoint_Description: "",
                Affiliation_Legal_Business_Name: "UPMC",
                Use_Code: "",
                Use_Description: "",
                Other_Use_Description: "",
                Content_Type: "",
                Content_Description: "",
                Other_Content_Description: "",
                Affiliation_Address_Line_One: "600 Grant St",
                Affiliation_Address_Line_Two: "Floor 58",
                Affiliation_Address_City: "Pittsburgh",
                Affiliation_Address_State: "PA",
                Affiliation_Address_Country: "US",
                Affiliation_Address_Postal_Code: "152192702"
            }
        ]
    },
    {
        NPI: "3497898829",
        Entity_Type_Code: "Individual",
        Replacement_NPI: "",
        Employer_Identification_Number: "",
        ProviderOrganizationName_Legal_Business_Name: "",
        ProviderLastName_Legal_Name: "NAJASAPEENAPETALAN",
        Provider_First_Name: "PRIYA",
        Provider_Middle_Name: "J.",
        Provider_Name_Prefix_Text: "",
        Provider_Name_Suffix_Text: " ",
        Provider_Credential_Text: "M.D.",
        Provider_Other_Organization_Name: "",
        Provider_Other_Organization_Name_Type_Code: "",
        Provider_Other_Last_Name: "",
        Provider_Other_First_Name: "",
        Provider_Other_Middle_Name: "",
        Provider_Other_Name_Prefix_Text: "",
        Provider_Other_Name_Suffix_Text: "",
        Provider_Other_Credential_Text: "",
        Provider_Other_Last_Name_Type_Code: "",
        Provider_First_Line_Business_Mailing_Address: "5708 WOLFGANG SCHOOL RD",
        Provider_Second_Line_Business_Mailing_Address: "",
        Provider_Business_Mailing_Address_City_Name: "GLEN ROCK",
        Provider_Business_Mailing_Address_State_Name: "PA",
        Provider_Business_Mailing_Address_Postal_Code: "173278891",
        Provider_Business_Mailing_Address_Country_Code: "US",
        Provider_Business_Mailing_Address_Telephone_Number: "7172354178",
        Provider_Business_Mailing_Address_Fax_Number: "",
        Provider_First_Line_Business_Practice_Location_Address: "5708 WOLFGANG SCHOOL RD",
        Provider_Second_Line_Business_Practice_Location_Address: "",
        Provider_Business_Practice_Location_Address_City_Name: "GLEN ROCK",
        Provider_Business_Practice_Location_Address_State_Name: "PA",
        Provider_Business_Practice_Location_Address_Postal_Code: "173278891",
        Provider_Business_Practice_Location_Address_Country_Code: "US",
        Provider_Business_Practice_Location_Address_Telephone_Number: "7172354178",
        Provider_Business_Practice_Location_Address_Fax_Number: "",
        Provider_Enumeration_Date: "02/15/2007",
        Last_Update_Date: "07/08/2007",
        NPI_Deactivation_Reason_Code: "",
        NPI_Deactivation_Date: "",
        NPI_Reactivation_Date: "",
        Provider_Gender_Code: "M",
        Authorized_Official_Last_Name: "",
        Authorized_Official_First_Name: "",
        Authorized_Official_Middle_Name: "",
        Authorized_Official_Title_Or_Position: "",
        Authorized_Official_Telephone_Number: "",
        Is_Sole_Proprietor: "Yes",
        Is_Organization_Subpart: "",
        Parent_Organization_LBN: "",
        Parent_Organization_TIN: "",
        Authorized_Official_Name_Prefix_Text: "",
        Authorized_Official_Name_Suffix_Text: "",
        Authorized_Official_Credential_Text: "",
        Certification_Date: "",
        HealthcareProviderData: [
            {
                Healthcare_Provider: "Healthcare Provider 1",
                Healthcare_Provider_Taxonomy_Code: "2084P0800X",
                Provider_License_Number: "MD020407E",
                Provider_License_Number_State_Code: "PA",
                Healthcare_Provider_Primary_Taxonomy_Switch: "Yes"
            }
        ],
        HealthcareProviderTaxonomyGroupData: [],
        OtherProviderData: [],
        OtherNameReferenceLayout: [],
        PracticeLocationReferenceLayout: [],
        Endpoint_Layout: []
    },
    {
        NPI: "4811972656",
        Entity_Type_Code: "Individual",
        Replacement_NPI: "",
        Employer_Identification_Number: "",
        ProviderOrganizationName_Legal_Business_Name: "",
        ProviderLastName_Legal_Name: "NG",
        Provider_First_Name: "KIM SOO",
        Provider_Middle_Name: "",
        Provider_Name_Prefix_Text: "DR.",
        Provider_Name_Suffix_Text: " ",
        Provider_Credential_Text: "M.D.",
        Provider_Other_Organization_Name: "",
        Provider_Other_Organization_Name_Type_Code: "",
        Provider_Other_Last_Name: "",
        Provider_Other_First_Name: "",
        Provider_Other_Middle_Name: "",
        Provider_Other_Name_Prefix_Text: "",
        Provider_Other_Name_Suffix_Text: "",
        Provider_Other_Credential_Text: "",
        Provider_Other_Last_Name_Type_Code: "",
        Provider_First_Line_Business_Mailing_Address: "PO BOX 5024",
        Provider_Second_Line_Business_Mailing_Address: "",
        Provider_Business_Mailing_Address_City_Name: "NEW YORK",
        Provider_Business_Mailing_Address_State_Name: "NY",
        Provider_Business_Mailing_Address_Postal_Code: "100875024",
        Provider_Business_Mailing_Address_Country_Code: "US",
        Provider_Business_Mailing_Address_Telephone_Number: "8006274470",
        Provider_Business_Mailing_Address_Fax_Number: "4129375710",
        Provider_First_Line_Business_Practice_Location_Address: "1 GUSTAVE L LEVY PL",
        Provider_Second_Line_Business_Practice_Location_Address: "ANESTHESIOLOGY - BOX 1010",
        Provider_Business_Practice_Location_Address_City_Name: "NEW YORK",
        Provider_Business_Practice_Location_Address_State_Name: "NY",
        Provider_Business_Practice_Location_Address_Postal_Code: "100296500",
        Provider_Business_Practice_Location_Address_Country_Code: "US",
        Provider_Business_Practice_Location_Address_Telephone_Number: "8006274470",
        Provider_Business_Practice_Location_Address_Fax_Number: "4129375767",
        Provider_Enumeration_Date: "12/14/2005",
        Last_Update_Date: "01/09/2015",
        NPI_Deactivation_Reason_Code: "",
        NPI_Deactivation_Date: "",
        NPI_Reactivation_Date: "",
        Provider_Gender_Code: "M",
        Authorized_Official_Last_Name: "",
        Authorized_Official_First_Name: "",
        Authorized_Official_Middle_Name: "",
        Authorized_Official_Title_Or_Position: "",
        Authorized_Official_Telephone_Number: "",
        Is_Sole_Proprietor: "No",
        Is_Organization_Subpart: "",
        Parent_Organization_LBN: "",
        Parent_Organization_TIN: "",
        Authorized_Official_Name_Prefix_Text: "",
        Authorized_Official_Name_Suffix_Text: "",
        Authorized_Official_Credential_Text: "",
        Certification_Date: "",
        HealthcareProviderData: [
            {
                Healthcare_Provider: "Healthcare Provider 1",
                Healthcare_Provider_Taxonomy_Code: "207L00000X",
                Provider_License_Number: "156749",
                Provider_License_Number_State_Code: "NY",
                Healthcare_Provider_Primary_Taxonomy_Switch: "Yes"
            }
        ],
        HealthcareProviderTaxonomyGroupData: [],
        OtherProviderData: [
            {
                Provider: "Provider 1",
                Other_Provider_Identifier: "00958347",
                Other_Provider_Identifier_Type_Code: "MEDICAID",
                Other_Provider_Identifier_State: "NY",
                Other_Provider_Identifier_Issuer: ""
            }
        ],
        OtherNameReferenceLayout: [],
        PracticeLocationReferenceLayout: [],
        Endpoint_Layout: []
    },
    {
        NPI: "5033112214",
        Entity_Type_Code: "Individual",
        Replacement_NPI: "",
        Employer_Identification_Number: "",
        ProviderOrganizationName_Legal_Business_Name: "",
        ProviderLastName_Legal_Name: "CAPPELLI",
        Provider_First_Name: "BAER",
        Provider_Middle_Name: "",
        Provider_Name_Prefix_Text: "",
        Provider_Name_Suffix_Text: " ",
        Provider_Credential_Text: "M.D.",
        Provider_Other_Organization_Name: "",
        Provider_Other_Organization_Name_Type_Code: "",
        Provider_Other_Last_Name: "",
        Provider_Other_First_Name: "",
        Provider_Other_Middle_Name: "",
        Provider_Other_Name_Prefix_Text: "",
        Provider_Other_Name_Suffix_Text: "",
        Provider_Other_Credential_Text: "",
        Provider_Other_Last_Name_Type_Code: "",
        Provider_First_Line_Business_Mailing_Address: "11279 PERRY HWY",
        Provider_Second_Line_Business_Mailing_Address: "STE 450",
        Provider_Business_Mailing_Address_City_Name: "WEXFORD",
        Provider_Business_Mailing_Address_State_Name: "PA",
        Provider_Business_Mailing_Address_Postal_Code: "150909303",
        Provider_Business_Mailing_Address_Country_Code: "US",
        Provider_Business_Mailing_Address_Telephone_Number: "",
        Provider_Business_Mailing_Address_Fax_Number: "",
        Provider_First_Line_Business_Practice_Location_Address: "604 EPSILON DR",
        Provider_Second_Line_Business_Practice_Location_Address: "",
        Provider_Business_Practice_Location_Address_City_Name: "PITTSBURGH",
        Provider_Business_Practice_Location_Address_State_Name: "PA",
        Provider_Business_Practice_Location_Address_Postal_Code: "152382808",
        Provider_Business_Practice_Location_Address_Country_Code: "US",
        Provider_Business_Practice_Location_Address_Telephone_Number: "4129679090",
        Provider_Business_Practice_Location_Address_Fax_Number: "",
        Provider_Enumeration_Date: "05/23/2005",
        Last_Update_Date: "03/25/2021",
        NPI_Deactivation_Reason_Code: "",
        NPI_Deactivation_Date: "",
        NPI_Reactivation_Date: "",
        Provider_Gender_Code: "M",
        Authorized_Official_Last_Name: "",
        Authorized_Official_First_Name: "",
        Authorized_Official_Middle_Name: "",
        Authorized_Official_Title_Or_Position: "",
        Authorized_Official_Telephone_Number: "",
        Is_Sole_Proprietor: "No",
        Is_Organization_Subpart: "",
        Parent_Organization_LBN: "",
        Parent_Organization_TIN: "",
        Authorized_Official_Name_Prefix_Text: "",
        Authorized_Official_Name_Suffix_Text: "",
        Authorized_Official_Credential_Text: "",
        Certification_Date: "",
        HealthcareProviderData: [
            {
                Healthcare_Provider: "Healthcare Provider 1",
                Healthcare_Provider_Taxonomy_Code: "208000000X",
                Provider_License_Number: "MD022712E",
                Provider_License_Number_State_Code: "PA",
                Healthcare_Provider_Primary_Taxonomy_Switch: "Yes"
            }
        ],
        HealthcareProviderTaxonomyGroupData: [],
        OtherProviderData: [],
        OtherNameReferenceLayout: [],
        PracticeLocationReferenceLayout: [],
        Endpoint_Layout: [
            {
                Endpoint_Type: "DIRECT",
                Endpoint_Type_Description: "Direct Messaging Address",
                Endpoint: "mark.a.koenig@upmcdirect.com",
                Affiliation: "Y",
                Endpoint_Description: "",
                Affiliation_Legal_Business_Name: "UPMC",
                Use_Code: "",
                Use_Description: "",
                Other_Use_Description: "",
                Content_Type: "",
                Content_Description: "",
                Other_Content_Description: "",
                Affiliation_Address_Line_One: "600 Grant St",
                Affiliation_Address_Line_Two: "Floor 58",
                Affiliation_Address_City: "Pittsburgh",
                Affiliation_Address_State: "PA",
                Affiliation_Address_Country: "US",
                Affiliation_Address_Postal_Code: "152192702"
            }
        ]
    },
    {
        NPI: "7497898829",
        Entity_Type_Code: "Individual",
        Replacement_NPI: "",
        Employer_Identification_Number: "",
        ProviderOrganizationName_Legal_Business_Name: "",
        ProviderLastName_Legal_Name: "KRZYJZPIAK",
        Provider_First_Name: "EDMUND",
        Provider_Middle_Name: "B.",
        Provider_Name_Prefix_Text: "",
        Provider_Name_Suffix_Text: " ",
        Provider_Credential_Text: "M.D.",
        Provider_Other_Organization_Name: "",
        Provider_Other_Organization_Name_Type_Code: "",
        Provider_Other_Last_Name: "",
        Provider_Other_First_Name: "",
        Provider_Other_Middle_Name: "",
        Provider_Other_Name_Prefix_Text: "",
        Provider_Other_Name_Suffix_Text: "",
        Provider_Other_Credential_Text: "",
        Provider_Other_Last_Name_Type_Code: "",
        Provider_First_Line_Business_Mailing_Address: "5708 WOLFGANG SCHOOL RD",
        Provider_Second_Line_Business_Mailing_Address: "",
        Provider_Business_Mailing_Address_City_Name: "GLEN ROCK",
        Provider_Business_Mailing_Address_State_Name: "PA",
        Provider_Business_Mailing_Address_Postal_Code: "173278891",
        Provider_Business_Mailing_Address_Country_Code: "US",
        Provider_Business_Mailing_Address_Telephone_Number: "7172354178",
        Provider_Business_Mailing_Address_Fax_Number: "",
        Provider_First_Line_Business_Practice_Location_Address: "5708 WOLFGANG SCHOOL RD",
        Provider_Second_Line_Business_Practice_Location_Address: "",
        Provider_Business_Practice_Location_Address_City_Name: "GLEN ROCK",
        Provider_Business_Practice_Location_Address_State_Name: "PA",
        Provider_Business_Practice_Location_Address_Postal_Code: "173278891",
        Provider_Business_Practice_Location_Address_Country_Code: "US",
        Provider_Business_Practice_Location_Address_Telephone_Number: "7172354178",
        Provider_Business_Practice_Location_Address_Fax_Number: "",
        Provider_Enumeration_Date: "02/15/2007",
        Last_Update_Date: "07/08/2007",
        NPI_Deactivation_Reason_Code: "",
        NPI_Deactivation_Date: "",
        NPI_Reactivation_Date: "",
        Provider_Gender_Code: "M",
        Authorized_Official_Last_Name: "",
        Authorized_Official_First_Name: "",
        Authorized_Official_Middle_Name: "",
        Authorized_Official_Title_Or_Position: "",
        Authorized_Official_Telephone_Number: "",
        Is_Sole_Proprietor: "Yes",
        Is_Organization_Subpart: "",
        Parent_Organization_LBN: "",
        Parent_Organization_TIN: "",
        Authorized_Official_Name_Prefix_Text: "",
        Authorized_Official_Name_Suffix_Text: "",
        Authorized_Official_Credential_Text: "",
        Certification_Date: "",
        HealthcareProviderData: [
            {
                Healthcare_Provider: "Healthcare Provider 1",
                Healthcare_Provider_Taxonomy_Code: "2084P0800X",
                Provider_License_Number: "MD020407E",
                Provider_License_Number_State_Code: "PA",
                Healthcare_Provider_Primary_Taxonomy_Switch: "Yes"
            }
        ],
        HealthcareProviderTaxonomyGroupData: [],
        OtherProviderData: [],
        OtherNameReferenceLayout: [],
        PracticeLocationReferenceLayout: [],
        Endpoint_Layout: []
    },
    {
        NPI: "8811972656",
        Entity_Type_Code: "Individual",
        Replacement_NPI: "",
        Employer_Identification_Number: "",
        ProviderOrganizationName_Legal_Business_Name: "",
        ProviderLastName_Legal_Name: "WARE",
        Provider_First_Name: "WILLIAN",
        Provider_Middle_Name: "L",
        Provider_Name_Prefix_Text: "DR.",
        Provider_Name_Suffix_Text: " ",
        Provider_Credential_Text: "M.D.",
        Provider_Other_Organization_Name: "",
        Provider_Other_Organization_Name_Type_Code: "",
        Provider_Other_Last_Name: "",
        Provider_Other_First_Name: "",
        Provider_Other_Middle_Name: "",
        Provider_Other_Name_Prefix_Text: "",
        Provider_Other_Name_Suffix_Text: "",
        Provider_Other_Credential_Text: "",
        Provider_Other_Last_Name_Type_Code: "",
        Provider_First_Line_Business_Mailing_Address: "PO BOX 5024",
        Provider_Second_Line_Business_Mailing_Address: "",
        Provider_Business_Mailing_Address_City_Name: "NEW YORK",
        Provider_Business_Mailing_Address_State_Name: "NY",
        Provider_Business_Mailing_Address_Postal_Code: "100875024",
        Provider_Business_Mailing_Address_Country_Code: "US",
        Provider_Business_Mailing_Address_Telephone_Number: "8006274470",
        Provider_Business_Mailing_Address_Fax_Number: "4129375710",
        Provider_First_Line_Business_Practice_Location_Address: "1 GUSTAVE L LEVY PL",
        Provider_Second_Line_Business_Practice_Location_Address: "ANESTHESIOLOGY - BOX 1010",
        Provider_Business_Practice_Location_Address_City_Name: "NEW YORK",
        Provider_Business_Practice_Location_Address_State_Name: "NY",
        Provider_Business_Practice_Location_Address_Postal_Code: "100296500",
        Provider_Business_Practice_Location_Address_Country_Code: "US",
        Provider_Business_Practice_Location_Address_Telephone_Number: "8006274470",
        Provider_Business_Practice_Location_Address_Fax_Number: "4129375767",
        Provider_Enumeration_Date: "12/14/2005",
        Last_Update_Date: "01/09/2015",
        NPI_Deactivation_Reason_Code: "",
        NPI_Deactivation_Date: "",
        NPI_Reactivation_Date: "",
        Provider_Gender_Code: "M",
        Authorized_Official_Last_Name: "",
        Authorized_Official_First_Name: "",
        Authorized_Official_Middle_Name: "",
        Authorized_Official_Title_Or_Position: "",
        Authorized_Official_Telephone_Number: "",
        Is_Sole_Proprietor: "No",
        Is_Organization_Subpart: "",
        Parent_Organization_LBN: "",
        Parent_Organization_TIN: "",
        Authorized_Official_Name_Prefix_Text: "",
        Authorized_Official_Name_Suffix_Text: "",
        Authorized_Official_Credential_Text: "",
        Certification_Date: "",
        HealthcareProviderData: [
            {
                Healthcare_Provider: "Healthcare Provider 1",
                Healthcare_Provider_Taxonomy_Code: "207L00000X",
                Provider_License_Number: "156749",
                Provider_License_Number_State_Code: "NY",
                Healthcare_Provider_Primary_Taxonomy_Switch: "Yes"
            }
        ],
        HealthcareProviderTaxonomyGroupData: [],
        OtherProviderData: [
            {
                Provider: "Provider 1",
                Other_Provider_Identifier: "00958347",
                Other_Provider_Identifier_Type_Code: "MEDICAID",
                Other_Provider_Identifier_State: "NY",
                Other_Provider_Identifier_Issuer: ""
            }
        ],
        OtherNameReferenceLayout: [],
        PracticeLocationReferenceLayout: [],
        Endpoint_Layout: []
    },
]
